/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_ptiseis;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AskisiData extends JFrame {
    JFrame parent;
    DefaultTableModel tableModel;
    /**
     * Creates new form pilotData
     */
    public AskisiData(JFrame parent) {
        this.parent=parent;
        initComponents();
        parent.setEnabled(false);
        tableModel = (DefaultTableModel)askisiTable.getModel();
        askisiTable.setSelectionMode(NORMAL);
        askisiList = askisiQuery.getResultList();
        fillTable();
    }

    // Προσθήκη δεδομένων στον πίνακα των ασκήσεων
    private void fillTable(){
        for(Askisi a:askisiList){
            addAskisi(a);
        }
    }
    
    public void newAskisi(Askisi a){
        addAskisi(a);
        this.askisiList.add(a);
    }

    public void removeAskisi(int row){
        this.askisiList.remove(row);
        this.tableModel.removeRow(row);
        
    }
    
    // Προσθήκη γραμμής στον πίνακα
    private void addAskisi(Askisi a){
        Vector aeroskafosRow = new Vector();
        aeroskafosRow.add(a.getId());
        aeroskafosRow.add(a.getPlithosEm());
        aeroskafosRow.add(a.getPlithosAp());
        aeroskafosRow.add(a.getIsxysEm());
        aeroskafosRow.add(a.getIsxysAp());
        tableModel.addRow(aeroskafosRow);
    }
    
    // Εισαγωγή τροποποιημένου άσκησης στον πίνακα ασκήσεων
    public void editAskisi(Askisi a, int row){
        int noRows=tableModel.getRowCount();
        // Διαγράφουμε την γραμμή
        tableModel.removeRow(row);
        this.askisiList.remove(row);
        addAskisi(a);
        tableModel.moveRow(noRows-1, noRows-1, row);
        askisiList.add(row, a);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        ProgrammaPtisewnPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Program_PtiseisPU").createEntityManager();
        askisiQuery = java.beans.Beans.isDesignTime() ? null : ProgrammaPtisewnPUEntityManager.createQuery("SELECT a FROM Askisi a");
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        askisiTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false; }} ;
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        insertButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));

        jButton5.setText("ΈΞΟΔΟΣ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        askisiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Πλήθος Εμπ", "Πλήθος Απ", "Ισχύς Εμπ", "Ισχύς Απ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(askisiTable);

        jLabel7.setText(">> Αρχείο");

        jLabel6.setText("Αρχείο >> Ασκήσεις ");

        insertButton.setText("Εισαγωγή");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Διαγραφή");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Επεξεργασία");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, editButton, insertButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(135, 135, 135)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        parent.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        AskisiForm af = new AskisiForm(this, true, MainMenu.NEW, null, -1);
        af.setLocation(350,50);
        af.setTitle("Εισαγωγή Άσκησης");
        af.setVisible(true);
    }//GEN-LAST:event_insertButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int row=this.askisiTable.getSelectedRow();
        if(row==-1)
            JOptionPane.showMessageDialog(this, "Επιλέξτε Αεροσκάφος");
        else {
            Askisi a = this.askisiList.get(row);
            AskisiForm af = new AskisiForm(this, true, MainMenu.DELETE, a, row);
            af.setLocation(350,50);
            af.setTitle("Διαγραφή Άσκησης");
            af.setVisible(true);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int row=this.askisiTable.getSelectedRow();
        if(row==-1)
            JOptionPane.showMessageDialog(this, "Επιλέξτε Αεροσκάφος");
        else {
            Askisi a = this.askisiList.get(row);
            AskisiForm af = new AskisiForm(this, true, MainMenu.EDIT, a, row);
            af.setLocation(350,50);
            af.setTitle("Επεξεργασία Άσκησης");
            af.setVisible(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ProgrammaPtisewnPUEntityManager;
    private javax.persistence.Query askisiQuery;
    private javax.swing.JTable askisiTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    List<Askisi> askisiList=new ArrayList();
}
