/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_ptiseis;

import javax.swing.JOptionPane;

/**
 *
 * @author antonis
 */
public class AskisiForm extends javax.swing.JDialog {

    /**
     * Creates new form PilotForm
     */
 
    Askisi askisi;
    int row;
    AskisiData parent;
    int operation;
    
    public AskisiForm(AskisiData parent, boolean modal, int operation, Askisi askisi, int row) {
        super(parent, modal);
        this.parent=parent;
        this.operation = operation;
        this.askisi=askisi;
        this.row=row;
        initComponents();
        // Αν επεξεργάζομαστε υπάρχον αεροσκάφος
        if (operation == MainMenu.EDIT || operation == MainMenu.DELETE){
            fillData();
            this.idField.setEditable(false);
        }
        if (operation == MainMenu.DELETE){
            disableForm();
            this.jButton1.setText("Διαγραφή");
        }
    }

    // Αυτόματη συμπλήρωση στοιχείων στη φόρμα
    public void fillData(){
        this.idField.setText(""+askisi.getId());
        this.plithosEmField.setText(String.valueOf(askisi.getPlithosEm()));
        this.plithosApField.setText(String.valueOf(askisi.getPlithosAp()));
        this.isxysApField.setText(String.valueOf(askisi.getIsxysAp()));        
        this.isxysEmField.setText(String.valueOf(askisi.getIsxysEm()));

    }
    
    
    public void disableForm(){
        this.plithosApField.setEditable(false);
        this.plithosEmField.setEditable(false);
        this.isxysEmField.setEditable(false);
        this.isxysApField.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        plithosEmField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        plithosApField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        isxysEmField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        isxysApField = new javax.swing.JTextField();

        jCheckBox6.setText("jCheckBox6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText(" Πλήθος Εμπ:");

        plithosEmField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plithosEmFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Πλήθος Απ:");

        jButton1.setText("Αποθήκευση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Έξοδος");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        idLabel.setText("ID:");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        jLabel5.setText(" Ισχύς Εμπ:");

        jLabel6.setText(" Ισχύς Απ:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(plithosEmField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plithosApField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(isxysApField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(isxysEmField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plithosEmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plithosApField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isxysEmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isxysApField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String idStr = idField.getText();
        int plithosEm, plithosAp, isxysEm, isxysAp;
        String plithosEmStr = plithosEmField.getText();
        String plithosApStr = plithosApField.getText();
        String isxysEmStr = isxysEmField.getText();
        String isxysApStr = isxysApField.getText();
        
        Askisi a;
        if(plithosEmStr.length()==0 || plithosApStr.length()==0 || idStr.length()==0
                || isxysEmStr.length()==0 || isxysApStr.length()==0)
            JOptionPane.showMessageDialog(this, "Ελλειπή στοιχεία");
        else {
            try{
                plithosEm=Integer.valueOf(plithosEmStr);
                plithosAp=Integer.valueOf(plithosApStr);
                isxysEm=Integer.valueOf(isxysEmStr);
                isxysAp=Integer.valueOf(isxysApStr);
                if(operation == MainMenu.NEW){
                    //Δημιουργία νέου αεροσκάφους
                    a = new Askisi(idStr);
                    a.setPlithosAp(plithosAp);
                    a.setPlithosEm(plithosEm);
                    a.setIsxysEm(isxysEm);
                    a.setIsxysAp(isxysAp);

                    DBManager.saveObject(a);
                    parent.newAskisi(a);
                }else if (operation == MainMenu.EDIT){
                    askisi.setPlithosAp(plithosAp);
                    askisi.setPlithosEm(plithosEm);
                    askisi.setIsxysEm(isxysEm);
                    askisi.setIsxysAp(isxysAp);
                    DBManager.modifyObject(askisi);
                    parent.editAskisi(askisi, row);
                } else {
                    // Διαγραφή Άσκησης
                    DBManager.deleteObject(askisi);
                    parent.removeAskisi(row);
                }
                dispose();
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(this, "Λανθασμένη τιμή");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά την αποθήκευση");
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void plithosEmFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plithosEmFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plithosEmFieldActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField isxysApField;
    private javax.swing.JTextField isxysEmField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField plithosApField;
    private javax.swing.JTextField plithosEmField;
    // End of variables declaration//GEN-END:variables
}
