/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_ptiseis;

import javax.swing.JOptionPane;

/**
 *
 * @author antonis
 */
public class PilotForm extends javax.swing.JDialog {

    /**
     * Creates new form PilotForm
     */
    Pilot pilot;
    int row;
    PilotData parent;
    int operation;
    
    public PilotForm(PilotData parent, boolean modal, int operation, Pilot pilot, int row) {
        super(parent, modal);
        this.parent=parent;
        this.operation = operation;
        this.pilot=pilot;
        this.row=row;
        initComponents();
        // Αν επεξεργάζομαστε υπάρχοντα πιλότο
        if (operation == MainMenu.EDIT || operation == MainMenu.DELETE){
            fillData();
            this.idField.setEditable(false);
        }
        if (operation == MainMenu.DELETE){
            disableForm();
            this.jButton1.setText("Διαγραφή");
        }
    }

    // Αυτόματη συμπλήρωση στοιχείων στη φόρμα
    public void fillData(){
        this.lnameField.setText(pilot.getLastname());
        this.fnameField.setText(pilot.getFirstname());
        this.idField.setText(""+pilot.getId());
        this.examHoursField.setText(String.valueOf(pilot.getHoursexam()));
        this.totalHoursField.setText(String.valueOf(pilot.getTotalhours()));
        
        if(pilot.getPic() == 1)
            this.jCheckBox2.setSelected(true);
        else
            this.jCheckBox2.setSelected(false);
        if(pilot.getEm() == 1)
            this.jCheckBox3.setSelected(true);
        else
            this.jCheckBox3.setSelected(false);
        if(pilot.getEkpaideytis() == 1)
            this.jCheckBox4.setSelected(true);
        else
            this.jCheckBox4.setSelected(false);
        if(pilot.getDokimastis() == 1)
            this.jCheckBox5.setSelected(true);
        else
            this.jCheckBox5.setSelected(false);
        if(pilot.getCommander() == 1)
            this.jCheckBox7.setSelected(true);
        else
            this.jCheckBox7.setSelected(false);
    }
    
    
    public void disableForm(){
        this.fnameField.setEditable(false);
        this.lnameField.setEditable(false);
        this.examHoursField.setEditable(false);
        this.totalHoursField.setEditable(false);
        this.jCheckBox2.setEnabled(false);
        this.jCheckBox3.setEnabled(false);
        this.jCheckBox4.setEnabled(false);
        this.jCheckBox5.setEnabled(false);
        this.jCheckBox7.setEnabled(false);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        lnameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        totalHoursField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        examHoursField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();

        jCheckBox6.setText("jCheckBox6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Επώνυμο:");

        jLabel2.setText("Όνομα:");

        jCheckBox2.setText("PiC");

        jCheckBox3.setText("Έμπειρος");

        jCheckBox4.setText("Εκπαιδευτής");

        jCheckBox5.setText("Δοκιμαστής");

        jCheckBox7.setText("Αρχηγός");

        jLabel3.setText("Συν. Ώρες");

        totalHoursField.setText(" ");

        jLabel4.setText("Ώρες Εξαμ.");

        examHoursField.setText(" ");

        jButton1.setText("Αποθήκευση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Έξοδος");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        idLabel.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(examHoursField))
                                    .addComponent(totalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(examHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String lname = lnameField.getText();
        String fname = fnameField.getText();
        String idStr = idField.getText();
        float totalHours, examHours;
        int id;
        String totalHoursStr = totalHoursField.getText();
        String examHoursStr = examHoursField.getText();
        Pilot p;
        if(lname.length()==0 || fname.length()==0 || totalHoursStr.length()==0 
                || examHoursStr.length()==0 || idStr.length()==0)
            JOptionPane.showMessageDialog(this, "Ελλειπή στοιχεία");
        else {
            try{
                totalHours=Float.valueOf(totalHoursStr);
                examHours=Float.valueOf(examHoursStr);
                id = Integer.valueOf(idStr);
                if(operation == MainMenu.NEW){
                    //Δημιουργία νέου ιπτάμενου
                    p = new Pilot(id, fname, lname);
            
                    p.setAvailable((short)0);
                    if(this.jCheckBox2.isSelected())
                        p.setPic((short)1);
                    else
                        p.setPic((short)0);
                    if(this.jCheckBox3.isSelected())
                        p.setEm((short)1);
                    else
                        p.setEm((short)0);
                    if(this.jCheckBox4.isSelected())
                        p.setEkpaideytis((short)1);
                    else
                        p.setEkpaideytis((short)0);
                    if(this.jCheckBox5.isSelected())
                        p.setDokimastis((short)1);
                    else
                        p.setDokimastis((short)0);
                    if(this.jCheckBox7.isSelected())
                        p.setCommander((short)1);
                    else
                        p.setCommander((short)0);
                    p.setTotalhours(totalHours);
                    p.setHoursexam(examHours);
                    DBManager.saveObject(p);
                    parent.newPilot(p);
                }else if (operation == MainMenu.EDIT){
                    pilot.setFirstname(fname);
                    pilot.setLastname(lname);
                    pilot.setTotalhours(totalHours);
                    pilot.setHoursexam(examHours);

                    if(this.jCheckBox2.isSelected())
                        pilot.setPic((short)1);
                    else
                        pilot.setPic((short)0);
                    if(this.jCheckBox3.isSelected())
                        pilot.setEm((short)1);
                    else
                        pilot.setEm((short)0);
                    if(this.jCheckBox4.isSelected())
                        pilot.setEkpaideytis((short)1);
                    else
                        pilot.setEkpaideytis((short)0);
                    if(this.jCheckBox5.isSelected())
                        pilot.setDokimastis((short)1);
                    else
                        pilot.setDokimastis((short)0);
                    if(this.jCheckBox7.isSelected())
                        pilot.setCommander((short)1);
                    else
                        pilot.setCommander((short)0);
                    DBManager.modifyObject(pilot);
                    parent.editPilot(pilot, row);
                } else {
                    // Διαγραφή Ιπταμένου
                    DBManager.deleteObject(pilot);
                    parent.removePilot(row);
                }
                dispose();
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(this, "Λανθασμένη τιμή");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά την αποθήκευση");
            }
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField examHoursField;
    private javax.swing.JTextField fnameField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField totalHoursField;
    // End of variables declaration//GEN-END:variables
}
